services:
  - type: web
    name: hogwarts-store-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hogwarts-store-db
          property: connectionString

databases:
  - name: hogwarts-store-db
    databaseName: hogwarts_store
    user: hogwarts_user
