services:
  - type: web
    name: hogwarts-store-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.init_db_force && python -m src.seed_hp_products && gunicorn -w 4 -b 0.0.0.0:$PORT "src.app:create_app()"
    envVars:
      - key: FLASK_APP
        value: src/app:create_app()
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hogwarts-store-db
          property: connectionString


staticSites:
  - name: hogwarts-store-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hogwarts-store.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: hogwarts-store-db
    databaseName: hogwarts_store
    user: hogwarts_user